MoviesApp/MoviesMVC/Models/ErrorViewModel.cs
using System;

namespace MoviesMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MoviesApp/MoviesMVC/Controllers/GenreController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MoviesData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesMVC.Controllers
{
    public class GenreController : Controller
    {
        // GET: GenreController
        public ActionResult Index()
        {
            List<Genre> genres = GenreManager.GetGenres();
            return View(genres);
        }

        // GET: GenreController/Details/A
        public ActionResult Details(string id)
        {
            Genre selectedGenre = GenreManager.Find(id);
            ViewBag.Genre = selectedGenre.Name;
            List<Movie> movies = MovieManager.GetMoviesByGenre(id);
            return View(movies);
        }

        //// GET: GenreController/Create
        //public ActionResult Create()
        //{
        //    return View();
        //}

        //// POST: GenreController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: GenreController/Edit/5
        //public ActionResult Edit(int id)
        //{
        //    return View();
        //}

        //// POST: GenreController/Edit/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        //// GET: GenreController/Delete/5
        //public ActionResult Delete(int id)
        //{
        //    return View();
        //}

        //// POST: GenreController/Delete/5
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Delete(int id, IFormCollection collection)
        //{
        //    try
        //    {
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}
    }
}

MoviesApp/MoviesMVC/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MoviesMVC.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MoviesApp/MoviesMVC/Controllers/MovieController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using MoviesData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace MoviesMVC.Controllers
{
    public class MovieController : Controller
    {
        // GET: MovieController
        public ActionResult Index()
        {
            List<Movie> movies = null;
            try
            {
                movies = MovieManager.GetMovies();
            }
            catch
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
            }
            return View(movies);
        }

        // GET: MovieController/Details/5
        public ActionResult Details(int id)
        {
            Movie movie = MovieManager.getSelectedMovieById(id);
            return View(movie);
        }

        // GET: MovieController/Create
        public ActionResult Create()
        {
            try
            {
                //prepare list of genres for the drop down list and pass through the view bag
                var types = GenreManager.GetGenresAsKeyValuePairs();
                SelectList list = new SelectList(types, "Value", "Text");
                ViewBag.Genres = list;

                //return View();// by default it returns a view thats named the same as the method
                return View("Edit", new Movie()); // MovieId is 0
            }
            catch(Exception)
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction("Index");
            }
        }

        // POST: MovieController/Create
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Create(Movie movie) // what is collected on the form is Movie data
        //{
        //    try
        //    {
        //        MovieManager.AddMovie(movie);
        //        return RedirectToAction(nameof(Index));
        //    }
        //    catch
        //    {
        //        return View();
        //    }
        //}

        // GET: MovieController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                //prepare list of genres for the drop down list and pass through the view bag
                var types = GenreManager.GetGenresAsKeyValuePairs();
                SelectList list = new SelectList(types, "Value", "Text");
                ViewBag.Genres = list;

                Movie movie = MovieManager.getSelectedMovieById(id);
                return View(movie);
            }
            catch(Exception)
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction("Index");
            }
        }

        // POST: MovieController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, Movie movie) // form collection is a movie
        {
            try
            {
                if (id == 0) // create
                {
                    MovieManager.AddMovie(movie);
                    TempData["Message"] = $"{movie.Name} sucessfully added";
                    TempData["IsError"] = false;
                }
                else // Update
                {
                    MovieManager.UpdateMovie(id, movie);
                    TempData["Message"] = $"{movie.Name} sucessfully updated";
                    TempData["IsError"] = false;
                }
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction(nameof(Index));
            }
        }

        // GET: MovieController/Delete/5
        public ActionResult Delete(int id)
        {
            try
            {
                Movie movie = MovieManager.getSelectedMovieById(id);
                return View(movie);
            }
            catch
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction("Index");
            }
        }

        // POST: MovieController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Movie movie)
        {
            try
            {
                Movie oldMovie = MovieManager.getSelectedMovieById(id);
                MovieManager.DeleteMovie(id);
                TempData["Message"] = $"{oldMovie.Name} sucessfully updated";
                TempData["IsError"] = false;
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                TempData["Message"] = "Database connection problem. Try again later.";
                TempData["IsError"] = true;
                return RedirectToAction("Index");
            }
        }
    }
}

MoviesApp/MoviesMVC/Views/Movie/Delete.cshtml
@model MoviesData.Movie

@{
    ViewData["Title"] = "Delete Movies";
}

<h1>Delete Movies</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.GenreId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

MoviesApp/MoviesMVC/Views/Movie/Details.cshtml
@model MoviesData.Movie

@{
    ViewData["Title"] = "Movie Details";
}

<h1>Movie Details</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.MovieId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.MovieId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Year)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Year)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Rating)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Rating)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.GenreId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Edit", "Edit", new { id = Model.MovieId}) |
    <a asp-action="Index">Back to List</a>
</div>

MoviesApp/MoviesMVC/Views/Movie/Edit.cshtml
@model MoviesData.Movie

@{
    ViewData["Title"] = "Add/Edit Movies";
}

<h1>Add/Edit Movies</h1>

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            @*<div class="form-group">
                <label asp-for="MovieId" class="control-label"></label>
                <input asp-for="MovieId" class="form-control" />
                <span asp-validation-for="MovieId" class="text-danger"></span>
            </div>*@
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Year" class="control-label"></label>
                <input asp-for="Year" class="form-control" />
                <span asp-validation-for="Year" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Rating" class="control-label"></label>
                <input asp-for="Rating" class="form-control" />
                <span asp-validation-for="Rating" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="GenreId" class="control-label"></label>
                <select asp-items = "@ViewBag.Genres" asp-for="GenreId" class="form-control">

                </select>
                @*<input asp-for="GenreId" class="form-control" />*@
                <span asp-validation-for="GenreId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

MoviesApp/MoviesMVC/Views/Movie/Index.cshtml
@model IEnumerable<MoviesData.Movie>

@{
    ViewData["Title"] = "Movies List";
}

<h1>All Movies</h1>
@if(TempData["Message"] != null)
 {
    <h4 class="@((bool)TempData["IsError"]? "bg-danger": "bg-info") text-center text-light"> @TempData["Message"]</h4>
 }

@if (Model != null)
{
    <p>
        <a asp-action="Create">Create New</a>
    </p>
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Year)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Rating)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.GenreId)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
    @foreach (var item in Model)
    {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Year)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Rating)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Genre.Name)
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.MovieId }) |
                    @Html.ActionLink("Details", "Details", new { id = item.MovieId }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.MovieId })
                </td>
            </tr>
    }
        </tbody>
    </table>
}

MoviesApp/MoviesMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Movies App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MoviesMVC</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Movie" asp-action="Index">Movies</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Genre" asp-action="Index">Genres</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MoviesMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>