InlandMarinaData/InlandMarinaMVC/Models/ErrorViewModel.cs
using System;

namespace InlandMarinaMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using InlandMarinaData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using InlandMarinaMVC.Validations;

namespace InlandMarinaMVC.Controllers
{
    public class AccountController : Controller
    {
        //Route: /Account/Login
        public IActionResult Login(string returnUrl = "")
        {
            if (returnUrl != null)
                TempData["Return Url"] = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(Customer customer)
        {
            Customer cust = CustomerManager.Authenticate(customer.Username, customer.Password);
            if (cust == null)//authentication failed
            {
                return View(); // return to login page
            }
            //Get owner id from user if the user is a owner and store it in session object
            //if (cust.Role == "Owner")
            HttpContext.Session.SetInt32("CurrentCustomer", (int)cust.ID);
            //else
            //    HttpContext.Session.SetInt32("CurrentOwner", 0);

            // authentication passed
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, cust.FirstName + " " + cust.LastName),
                new Claim("FirstName", cust.FirstName),
                new Claim("LastName", cust.LastName),
                new Claim("Phone", cust.Phone),
                new Claim("City", cust.City),
            };
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies"); // cookie authentication
            ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            await HttpContext.SignInAsync("Cookies", claimsPrincipal);

            if (String.IsNullOrEmpty(TempData["Return Url"].ToString())) // no url found
            {
                return RedirectToAction("Index", "Home"); // return to main page
            }
            else
            {
                return Redirect(TempData["Return Url"].ToString()); // return to url
            }
        }
        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync("Cookies");
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home"); // return to main page
        }

        public IActionResult AccessDenied()
        {
            return View();
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Customer customer)
        {
            try
            {
                if (!IsStringUnique.IsValid(CustomerManager.GetAllUsernames(), customer.Username))
                    ModelState.AddModelError("Username", "Username already exists");
                if (ModelState.IsValid)
                {
                    CustomerManager.AddCustomer(customer);
                    return RedirectToAction("Index", "Home");
                } 
                else
                {
                    ModelState.AddModelError(string.Empty, "Please correct all errors");
                    return View(customer);
                }
            }
            catch
            {
                return View();
            }
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InlandMarinaMVC.Controllers
{
    public class ContactController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/DockController.cs
using InlandMarinaData;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InlandMarinaMVC.Controllers
{
    public class DockController : Controller
    {
        // GET: DockController
        public ActionResult Index()
        {
            List<Dock> docks = DockManager.GetDocks();
            return View(docks);
        }

        // GET: DockController/Details/5
        public ActionResult Details(int id)
        {
            List<Slip> slips = SlipManager.GetUnleasedSlipsByDocks(id);
            return View(slips);
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/HomeController.cs
using InlandMarinaMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace InlandMarinaMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/LeaseController.cs
using InlandMarinaData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InlandMarinaMVC.Controllers
{
    public class LeaseController : Controller
    {
        [Authorize]
        public ActionResult Index()
        {
            List<Slip> unleasedSlips = SlipManager.GetUnleasedSlips();
            return View(unleasedSlips);
        }
        [Authorize]
        public ActionResult AddLease(int id)
        {
            if(HttpContext.Session.GetInt32("CurrentCustomer") != null)
            {
                //customer leases a new slip
                LeaseManager.AddLease(id, (int)HttpContext.Session.GetInt32("CurrentCustomer"));
                return RedirectToAction("customerSlips","Slips");
            }
            List<Slip> unleasedSlips = SlipManager.GetUnleasedSlips();
            return View(unleasedSlips);
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Controllers/SlipsController.cs
using InlandMarinaData;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace InlandMarinaMVC.Controllers
{
    public class SlipsController : Controller
    {
        // GET: SlipsController
        public ActionResult Index()
        {
            List<Slip> unleasedSlips = SlipManager.GetUnleasedSlips();
            return View(unleasedSlips);
        }
        [Authorize]
        public ActionResult customerSlips()
        {
            if (HttpContext.Session.GetInt32("CurrentCustomer") != null)
            {
                List<Slip> custSlips = SlipManager.GetUnleasedSlipsByCustId((int)HttpContext.Session.GetInt32("CurrentCustomer"));
                return View(custSlips);
            }
                
            return View("Login","Account");
        }
    }
}

InlandMarinaData/InlandMarinaMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Inland Marina</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="https://kit.fontawesome.com/80f3d012e6.js" crossorigin="anonymous"></script>
    <link rel="icon" href="favicon.png">
</head>
<body>
    <header>
        <nav id="navBar" class="navbar navbar-expand-sm navbar-toggleable-sm border-bottom box-shadow mb-3 ">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src ="~/Resources/inlandLogo.png" id="Logo" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link " id="navLinks" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="navLinks" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="navLinks" asp-area="" asp-controller="Slips" asp-action="Index">Slips</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" id="navLinks" asp-area="" asp-controller="Dock" asp-action="Index">Docks</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial"/>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - InlandMarina - <a asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

InlandMarinaData/InlandMarinaMVC/Views/Slips/Index.cshtml
@model IEnumerable<InlandMarinaData.Slip>

@{
    ViewData["Title"] = "Slips";
}

<h1 id="WelcomeHeading">Slips</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ID)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Length)
            </td>
        </tr>
}
    </tbody>
</table>

InlandMarinaData/InlandMarinaMVC/Views/Slips/customerSlips.cshtml
@model IEnumerable<InlandMarinaData.Slip>

@{
    ViewData["Title"] = "customerSlips";
}

<h1>customerSlips</h1>

<p>
    <a asp-controller="Lease" asp-action="Index">Add Lease</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Width)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Length)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DockID)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Width)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Length)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DockID)
            </td>
        </tr>
}
    </tbody>
</table>