Rentals/RentalsMVC/Models/ErrorViewModel.cs
using System;

namespace RentalsMVC.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Rentals/RentalsMVC/Models/RentalViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace RentalsMVC.Models
{
    // view model for displaying rentals as read-only list
    public class RentalViewModel
    {
        public string Address { get; set; }
        public string City { get; set; }
        public string Province { get; set; }
        public string Rent { get; set; } // formatted Rent
        [Display(Name = "Propery Type")]
        public string PropertyType { get; set; } // Style of the property type
        public string Owner { get; set; } // Name of the owner
    }
}

Rentals/RentalsMVC/Controllers/AccountController.cs
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RentalsData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace RentalsMVC.Controllers
{
    public class AccountController : Controller
    {
        //Route: /Account/Login
        public IActionResult Login(string returnUrl="")
        {
            if (returnUrl != null)
                TempData["Return Url"] = returnUrl;
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> LoginAsync(User user)
        {
            User usr = UserManager.Authenticate(user.Username, user.Password);
            if(usr == null)//authentication failed
            {
                return View(); // return to login page
            }
            //Get owner id from user if the user is a owner and store it in session object
            if(usr.Role == "Owner")
                HttpContext.Session.SetInt32("CurrentOwner", (int)usr.OwnerId);
            else
               HttpContext.Session.SetInt32("CurrentOwner", 0);
            // authentication passed
            List<Claim> claims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, usr.Username),
                new Claim("FullName", usr.FullName),
                new Claim(ClaimTypes.Role, usr.Role),
            };
            ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims, "Cookies"); // cookie authentication
            ClaimsPrincipal claimsPrincipal = new ClaimsPrincipal(claimsIdentity);

            await HttpContext.SignInAsync("Cookies", claimsPrincipal);

            if (String.IsNullOrEmpty(TempData["Return Url"].ToString())) // no url found
            {
                return RedirectToAction("Index", "Rentals"); // return to main page
            }
            else
            {
                return Redirect(TempData["Return Url"].ToString()); // return to url
            }
        }
        public async Task<IActionResult> LogoutAsync()
        {
            await HttpContext.SignOutAsync("Cookies");
            return RedirectToAction("Index", "Rentals"); // return to main page
        }

        public IActionResult AccessDenied()
        {
            return View();
        }
    }
}

Rentals/RentalsMVC/Controllers/OwnersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using RentalsData;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RentalsMVC.Controllers
{
    [Authorize]
    public class OwnersController : Controller
    {
        // GET: OwnersController
        public ActionResult Index()
        {
            List<Owner> owners = OwnersManager.GetAll();
            return View(owners);
        }

        
        [Authorize(Roles = "Manager")]
        // GET: OwnersController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: OwnersController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Owner owner)
        {
            try
            {
                OwnersManager.Add(owner);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

       
    }
}

Rentals/RentalsMVC/Controllers/RentalsController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using RentalsData;
using RentalsMVC.Models;
using System.Collections;
using System.Collections.Generic;
using System.Linq;


namespace RentalsMVC.Controllers
{
    public class RentalsController : Controller
    {
        // GET: RentalsController
        public ActionResult Index()
        {
            List<RentalProperty> rentals = RentalsManager.GetAll();
            List<RentalViewModel> viewModels = rentals.Select(r => new RentalViewModel { 
                Address = r.Address,
                City = r.City,
                Province = r.Province,
                Rent = r.Rent.ToString("c"),
                PropertyType= r.PropertyType.Style,
                Owner = r.Owner.Name
            }).ToList();
            return View(viewModels);
        }

        // GET: RentalsController/List
        [Authorize]
        public ActionResult List()
        {
            List<RentalProperty> rentals = null;
            //get id of the current owner
            int? ownerId = HttpContext.Session.GetInt32("CurrentOwner");
            if (ownerId == null) // owner logged in
                ownerId = 0;
            ViewBag.OwnerId = (int)ownerId;
            rentals = RentalsManager.GetPropertiesByOwner((int)ownerId);
            return View(rentals);
        }
        //if current user is Owner then display filtered properties by current owner id
        //otherwise display all
        // GET: RentalsController/Create
        [Authorize (Roles = "Owner")]
        public ActionResult Create()
        {
            //get id of the current owner
            int? ownerId = HttpContext.Session.GetInt32("CurrentOwner");
            if (ownerId == null) // owner logged in
                ownerId = 0;

            ViewBag.OwnerId = (int)ownerId;
            ViewBag.PropertyTypes = GetPropertyTypes(); // property types to populate drop down
            return View(new RentalProperty());
        }

        // POST: RentalsController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(RentalProperty rental)
        {
            try
            {
                RentalsManager.Add(rental);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }   

        // auxilliary method for Create 
        protected IEnumerable GetPropertyTypes()
        {
            // call property types manager to get key/value pairs for property types drop down list 
            var types = PropertyTypesManager.GetAllAsKeyValuePairs();
            // convert it to a form that drop down list can use, and add to the bag
            var styles = new SelectList(types, "Value", "Text");
            var list = styles.ToList(); // to be able to use Insert method
            list.Insert(0, new SelectListItem
            {
                Value = "0",
                Text = "All Styles"
            });
            return list;
        }
    }
}

Rentals/RentalsMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Rentals App</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Rentals" asp-action="Index">Rentals App</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="Index">Rentals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Rentals" asp-action="List">My Rentals</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Owners" asp-action="Index">Owners</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />                    
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Rentals App 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>